INSERT INTO Skills(SID, STitle) VALUES (null, 'Java');
INSERT INTO Skills(SID, STitle) VALUES (null, 'C');
INSERT INTO Skills(SID, STitle) VALUES (null, 'C++');
INSERT INTO Skills(SID, STitle) VALUES (null, 'C#');
INSERT INTO Skills(SID, STitle) VALUES (null, 'HTML');
INSERT INTO Skills(SID, STitle) VALUES (null, 'CSS');
INSERT INTO Skills(SID, STitle) VALUES (null, 'PHP');
INSERT INTO Skills(SID, STitle) VALUES (null, 'JavaScript');
INSERT INTO Skills(SID, STitle) VALUES (null, 'AppleScript');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Python');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Lua');
INSERT INTO Skills(SID, STitle) VALUES (null, 'SQL');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Pascal');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Kotlin');
INSERT INTO Skills(SID, STitle) VALUES (null, 'XML');
INSERT INTO Skills(SID, STitle) VALUES (null, 'XHTML');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Perl');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Ruby');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Cobol');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Fortran');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Turing');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Visual Basic');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Web Design');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Networking');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Android');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Apple');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Mobile Applications');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Software Testing');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Linux');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Cyber Security');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Data Modeling');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Animation');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Graphic Design');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Video Game Design');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Server Maintenance');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Research Development');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Hardware');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Git');
INSERT INTO Skills(SID, STitle) VALUES (null, 'Database Design');